### ISSUE TITLE
Is there anyone working on sorting algorithms?

### ISSUE THREAD

**Issue by kimjy0126** [19-1-skku-oss/2019-1-OSS-E4#17]
I'm going to add some sorting algorithms, and I want to know if someone is working on the same algorithms with me.
Here are some sorting algorithms I wanted to add:
- Timsort
- Bozosort
- Librarysort
- Proxmapsort
- ...

If there is something that you're already working on, please notice me.

**Comment by kimjy0126** [comment]
Actually, I'm currently working on <b>Timsort</b> and <b>Bozosort</b>.

**Comment by kimjy0126** [comment]
I added <b>Bozosort</b> w/ pull request #18, and I'm keep working on <b>Timsort</b>.

**Comment by Son-GyeongSik** [comment]
난 지금 그래프 탐색 알고리즘 수정중임. (추가. 오일러 프로젝트 건드리고 있음)
소팅은 안건드릴듯 ㅋㅋㅋ

**Comment by kimjy0126** [comment]
I think I'm the only person who is working on sorting part, so I'll close this issue.
