### ISSUE TITLE
Need help on Timsort

### ISSUE THREAD

**Issue by kimjy0126** [19-1-skku-oss/2019-1-OSS-E4#26]
I'm working on Timsort as I noticed you on issue #17, but it's very difficult to understand for me.
If somebody understand this algorithm, please let me know how it works.

[Here](https://en.wikipedia.org/wiki/Timsort) is wikipedia page of Timsort.

P.S. Almost every implementation of Timsort in google is actually not the exact algorithm.

**Comment by CheFly1116** [comment]
I've implemented TimSort for my data structure introduction assignment.
I'll push my own code until this morning.

**Comment by kimjy0126** [comment]
Thanks! After checking that the code is uploaded well today, I'll close this issue.

**Comment by kimjy0126** [comment]
@CheFly1116 TimSort!

**Comment by CheFly1116** [comment]
Sorry :( I was busy for my Java Group Assignment I've pushed my Timsort Code into master branch.

**Comment by kimjy0126** [comment]
@CheFly1116 Still I cannot understand the code, but... it is not important. Renamed on pull request #41. Thank you for your support.
