### ISSUE TITLE
Is it necessary to keep proj/searching/PatternSearch directory?

### ISSUE THREAD

**Issue by kimjy0126** [19-1-skku-oss/2019-1-OSS-E4#28]
I <b>renamed all the source codes</b> on pull request #27, and I found this directory. There are three searching algorithms.
I think <b>removing this directory</b> and <b>moving these three searching algorithms to outside of the directory</b> is one of the good way to arrange the files.

What do you think about this?

**Comment by CheFly1116** [comment]
Instead removing directory, please make directory at each files and add README.md too.
We have to add explanation of these codes.

**Comment by kimjy0126** [comment]
oh, ok thx XD
